### ISSUE TITLE
SEP 047 -- Change direction of Namespace references

### ISSUE THREAD

**Issue by jakebeal** [SynBioDex/SEPs#102]
SBOL 3.0 set up Namespace to point to objects, which will tend to make Namespace objects extremely large. Instead, objects should point to their Namespace. This SEP proposes to reverse the direction of the relationship.

https://github.com/SynBioDex/SEPs/blob/master/sep_047.md

**Comment by cjmyers** [comment]
Are we sure we want to make hasNamespace required?  Also, just to be clear, non-Top Level objects inherit the namespace from their parent Top Level, correct?

**Comment by jakebeal** [comment]
non-TopLevel objects inherit from their parent, which either is a TopLevel or else itself recursively inherits from a TopLevel.

As for making it required: in Section 5.1 on URIs, we state: "A TopLevel URL MUST use the following pattern: `[namespace]/[local]/[displayId]`".  If hasNamespace is not required, then we can't check if an object follows the pattern.  Can you think of any situation in which that would be desirable?

**Comment by cjmyers** [comment]
I agree that it would be desirable to have it required, but I'm concerned about conversion from SBOL2 where the URI requirements did not exist.

**Comment by jakebeal** [comment]
I would suggest a dual approaches to conversion:

1. Request an optional namespace for conversion.  This may not be difficult, as many tools (e.g., SynBioHub, SBOLDesigner, SBOLCanvas) already effectively implement namespace conventions internally.
2. In the case where namespace is not provided, make a guess at namespace based on the most common prefix in TopLevel objects.  In most SBOL documents, there will be a shared stem at least at the server level, and in the case where there is more than one such, more than one namespace can be created.

I have updated the SEP accordingly, and also to discuss how this affects non-URL URIs.  @PrashantVaidyanathan , please look and comment, as your tools are affected by this.

**Comment by cjmyers** [comment]
This can work.  Indeed, this is pretty much what we do when we import an SBOL file with non-compliant URIs into SBH.  This turns out to be extremely difficult to get right, and it has been the source of numerous bugs in the library.  All that being said though, I think I've come around to making this required.  While it may make conversion tricky, if we don't bite the bullet then this problem will continue into further versions of SBOL.  Having the namespace will indeed simplify a lot of other operations in the future.

**Comment by PrashantVaidyanathan** [comment]
I apologize for the delay in replying to this. But Namespaces in general won't pose a problem any more for the tools I'm working on. This is primarily because we are thinking of adopting a notion of "aliases" that can point to various databases/repositories, where the alias doesn't have any constraint.

**Comment by jakebeal** [comment]
Thank you @PrashantVaidyanathan ; that sounds like we're clear then.
