### ISSUE TITLE
SEP 007 -- CombinatorialAssembly initial draft

### ISSUE THREAD

**Issue by graik** [SynBioDex/SEPs#21]
see evolving document in SEP github repo:
https://github.com/SynBioDex/SEPs/blob/master/sep_007.md

**Comment by bbartley** [comment]
The specification for the `strategy` property is contradictory with regards to whether it is required or optional.  See https://github.com/SynBioDex/SEPs/blob/master/sep_007.md#213-combinatorialderivationstrategy

**Comment by bbartley** [comment]
The `template` property is an unfortunate choice of name, since template is a reserved word in C++.  See https://github.com/SynBioDex/SEPs/blob/master/sep_007.md#211-combinatorialderivationtemplate

**Comment by bbartley** [comment]
`operator` is also a reserved word

**Comment by bbartley** [comment]
This SEP could be improved by listing the validation rules under their own section.  I see that Nic did discuss validation under Specification, but there seem to be quite a few rules, and it would be helpful if they were compiled into a list.

I'm working through implementing a prototype of this SEP in libSBOL, so that's why I'm logging all these issues.

**Comment by eoberortner** [comment]
Hi, 

I think the SEP is nice! Great job! I do have some questions though and would appreciate if you could shed some light on these:
1) Since CombinatorialDerivation represents a combinatorial design, why not just naming the class CombinatorialDesign?

2) CombinatorialDerivation requires a template. Two questions:
-- How do we ensure that the template ComponentDefinition has Components (representing the variables of the combinatorial design)? Some formal constraints must be provided in the spec. 
-- What if, I don't have a template? One alternative would be that VariableComponent points to itself, allowing to define some arrangement among the variables of the combinatorial design.

3) A VariableComponent MUST point to a Component of the template ComponentDefinition. How do you ensure this? Again, some formal constraints must be provided in the spec. Also, since I might not have a template, I cannot point to a Component.

4) I'm struggling to understand the semantics of the VariableComponent's operator. For example: assume operator OneOrMore and we have variantDerivations, variantCollections, and variants specified on the VariableComponent. What does the OneOrMore mean then?

Please let me know if I should post these questions on the sbol-dev group too. 

Thanks, 
Ernst

**Comment by palchicz** [comment]
Closing in accordance with changes to SEP issue tracking rules detailed in SEP 001 https://github.com/SynBioDex/SEPs/commit/bcbbcab01a2b01d5055fc55d03c949fb227e37d2#diff-44cec2aabf4c066f9a54ac4ef6634b9b
