### ISSUE TITLE
SEP 022 -- Rename displayId to id

### ISSUE THREAD

**Issue by udp** [SynBioDex/SEPs#54]
Full details in: https://github.com/SynBioDex/SEPs/blob/master/sep_022.md

**Comment by graik** [comment]
To give a "historic" perspective, we chose this name exactly to emphasize that `displayID` **should** indeed be shown to the end user. The idea was that a good `displayID` was short and memorable so that I could go and tell a colleague: "We used the tetRepressor R0040 from the iGem registry." With this information alone, she could then go and fetch the exact record. I think this is a simple but very important usability feature that we should keep insisting on.

**Comment by mikebissell** [comment]
Just a reminder: since SBOL's reference serialization is XML, any use of 'id' as an attribute name must be considered in light of XML (and maybe XSD, relaxng) conventions, syntax, uniqueness constraints, and other rules. 'id' is special.

Also, since displayId isn't really an SBOL entity's _**primary**_ unique identifier, it might not be appropriate to rename displayId to id. DisplayId is just a subsidiary identifier, basically a synonym.

See:
xsd:id
xsd:idref
https://www.w3.org/TR/xml-id/

**Comment by bbartley** [comment]
Hi, in the context of an SBOL-compliant URI the display ID is equivalent to a local identifier within a namespace, so I suggest changing `displayId` to `localId`

**Comment by graik** [comment]
This was very briefly touched on today, in the first SBOL 3 skype discussion. I like the `localId` suggestion. I think this would clarify things a little better. 

One concern raised was that URI (or was it RDF?) constraints mean that our current definition does not allow displayId to start with a number (it MUST start with `_` or letter). So a purely numeric identifier is currently forbidden. Personally, I can live with that though.

**Comment by udp** [comment]
+1 for localId/I'm happy to change the SEP to recommend that instead

It needs to be very explicit what "local" means though, as SBOL currently doesn't say much about context.  I guess this ties into Jake's proposal for a Namespace entity.

**Comment by cjmyers** [comment]
@udp has agreed to withdraw this SEP
