### ISSUE TITLE
SEP 024 - Best practices for host context / ontologies for experiments

### ISSUE THREAD

**Issue by cjmyers** [SynBioDex/SEPs#57]

**Comment by NeilWipat** [comment]
Update as of COMBINE 2018

Discussion has taken place. Nic has produced some additional diagrams which will be added to the current draft of the SEP.

**Comment by jakebeal** [comment]
[Link to SEP 024](https://github.com/SynBioDex/SEPs/blob/master/sep_024.md)

**Comment by chapmanb** [comment]
This proposal is a great overall structure for representing experimental work associated with a design. In donig some exploratory work, the one issue is the size of the NCIT ontology. It's awesome because it captures everything but is also unwieldy to work with due to the size. I've been using SciGraph as a path for lookups and references, and practically it chokes with memory issues trying to get it in. 

Does anyone have any experience slimming it down to be a bit more restricted, or otherwise working with it? I'd love to move to a single OBO ontology for associated experimental information. As some alternatives, so far I'd been using the BioAssay Ontology (BAO) (http://bioassayontology.org/) which has a lot of useful experimental terms but is not connected with other OBO ontologies. There is also the Ontology for Biomedical Investigations (OBI) (http://purl.obolibrary.org/obo/obi) recommended by the OBO team but it is missing useful terms so we've needed to supplement from BAO.

Thanks for any thoughts/pointers on folks working with this, it's great to have this work around consistent naming approaches.

**Comment by jakebeal** [comment]
In our use of NCIT so far, we've just been cherry-picking URIs and not attempting to actually load it in. I suspect we might be able to focus on only relevant subsets of the overall ontology.

Alternately, we have not previously worked with BAO: is the union of BAO+OBI sufficient to cover all of the examples that NCIT has? If so, that might be a good alternative to choose instead.

**Comment by goksel** [comment]
Should the measurements be added to ComponentDefinitions or to ComponentInstances?
How do we differentiate two different measurements for the same ComponentDefinition?

The same comment also applied to ModuleDefinition vs Module entities.

"Possible promotion of "measures" to Identified" is not clear. I believe, pretty much every entity in SBOL derives from Identified. Do we want to extend this for every SBOL entity?

**Comment by jakebeal** [comment]
A measurement on an instance refers to its attributes as measured in the
context of the larger system it is placed in, whereas a measurement on a
definition refers to a context-independent property.

Multiple measures are distinguished by the roles assigned to them, as
already specified in the accepted measurement SEP.

The move of the measure property to Identified is motivated by the
observation that we're adding more classes to have measures, and there is
no reason to expect that set to be bounded. Thus, we might as well extend
to all classes now rather than piecemeal, making library maintainers jobs
more difficult.

Thanks,
-Jake
(sent from my phone)

**Comment by chapmanb** [comment]
Jake;
Thanks for the additional information on how you'd envisioned using NCIT. If we could narrow it down that seems like a good choice since I'd love to use OBO ontologies that connect into that ecosystem. It's mostly that it's so big I'm not sure how to subset or break it down. For instance, positive control falls under "Miscellaneous Molecular Biology Terms", which doesn't give much for isolation:

https://www.ebi.ac.uk/ols/ontologies/ncit/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FNCIT_C64356

BAO does break this down under role, which matches a lot of thinking in this SEP:

https://www.ebi.ac.uk/ols/ontologies/bao/terms?iri=http%3A%2F%2Fwww.bioassayontology.org%2Fbao%23BAO_0000080

so seems a good fit. Other related terms, like inducer, group similarly:

https://www.ebi.ac.uk/ols/ontologies/bao/terms?iri=http%3A%2F%2Fwww.bioassayontology.org%2Fbao%23BAO_0003058

while NCIT falls under a different tree (Material -> Substance -> Chemical):

https://www.ebi.ac.uk/ols/ontologies/ncit/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FNCIT_C120268

The downside is still not being an OBO schema with external links but maybe the better representation makes up for it.

Thanks for talking through this, I'm definitely keen to hear other people's experiences and opinions.

**Comment by Fontanapink** [comment]
Hello people,
                       I've seen there hasn't been any more discussions
regarding this SEP in a while. If everybody is happy I can move it to a
vote soon.
Pedro

**Comment by palchicz** [comment]
Closing issue. There is still some work to be done incorporating measurements changes from SEP which are target for SBOL 2.4

**Comment by cjmyers** [comment]
So in a previously accepted SEP, SEP 24, there were 2 main propositions:

Some best practices propositions
Promoting measures to identified
The first point was intended for SBOL 3.2.1 and has been implemented into the specifications, however, we are still missing the second point, which in the original SEP read:

2.6 Possible promotion of "measures" to Identified
Given the number of other classes with a potential "measures" property to add in the future, we should also consider changing it to be on Identified rather than on individual classes.
This change was thought for SBOL 2.4.

**Comment by cjmyers** [comment]
Still need to update validation rules to promote Measure to identified.  Check text too.
