### ISSUE TITLE
SEP 032: Do not rename ontologicially defined predicates

### ISSUE THREAD

**Issue by palchicz** [SynBioDex/SEPs#74]
Linking https://github.com/SynBioDex/SEPs/blob/master/sep_032.md

**Comment by cjmyers** [comment]
There are two parts to this SEP, one part is changing "name" to "title".  Personally, I think "name" is a lot more clear than "title", and it is a lot more understandable to users, I think.  Having a column of titles in a list of parts seems like it would be highly non-intuitive to people.  So, I think we would end up changing the library, but still want to present this to users differently.  The only real complete solution I see is changing from using dcterms:title to sbol:name.  I think this would be my preferred approach.

As for the second part, sets of objects, I understand that "wasDerivedFroms" sounds odd.  However, this is never serialized.  This is not actually a difference between the term name and what is serialized.  When you want to add a wasDerivedFrom, you call the method "addWasDerivedFrom".  The only time you use the plural is when you want the set of objects, and you call something like, "getWasDerivedFroms".  While this one may sound strange, others like, "getModels" sounds perfectly fine.  I don't think I would throw out this convention just because a couple of the plurals sound awkward.  I think it would be much worse to call "getModel" and get a set.

**Comment by udp** [comment]
> There are two parts to this SEP, one part is changing "name" to "title". Personally, I think "name" is a lot more clear than "title", and it is a lot more understandable to users, I think. Having a column of titles in a list of parts seems like it would be highly non-intuitive to people. So, I think we would end up changing the library, but still want to present this to users differently. The only real complete solution I see is changing from using dcterms:title to sbol:name. I think this would be my preferred approach.

It's not necessarily about what sounds clearer, but about addressing this situation where we take existing terms from other ontologies and give them different names because we think they sound better.  These invented names exist only in the specification document and possibly the libraries.  They do not exist in SBOL XML files, SBOL in an RDF triplestore, or in SBOL SPARQL queries. This creates a pointless layer of confusion which I consider unacceptable.  While you could argue that it is only a minor issue, it is a contributing factor to the unnecessary complexity of SBOL.

> As for the second part, sets of objects, I understand that "wasDerivedFroms" sounds odd. However, this is never serialized. This is not actually a difference between the term name and what is serialized. When you want to add a wasDerivedFrom, you call the method "addWasDerivedFrom". The only time you use the plural is when you want the set of objects, and you call something like, "getWasDerivedFroms". While this one may sound strange, others like, "getModels" sounds perfectly fine. I don't think I would throw out this convention just because a couple of the plurals sound awkward. I think it would be much worse to call "getModel" and get a set

Sets exist in Java, but not in RDF.  We are currently trying to explain the SBOL data model as if it is a user manual for libSBOLj.  You can completely remove the clunky pluralisation "wasDerivedFroms" from the specification by describing the use of the prov:wasDerivedFrom term properly as this SEP suggests, and libSBOLj can still call the function "getWasDerivedFroms" if that's what libSBOLj wants to do.

There are not two separate issues in this SEP.  Pluralising the prov:wasDerivedFrom property to "wasDerivedFroms" is exactly the same as renaming "dcterms:title" to "name".  We should be completely clear about when and how we use terms from other ontologies, and we should describe our specification and its relation to other specifications clearly and in a way that is equally as useful to someone using an SBOL library, reading an SBOL Turtle file, or writing a SPARQL query.

**Comment by cjmyers** [comment]
My vote to fix dcterms:title then is to change it to sbol:name, and stop using dcterms:title in SBOL3.  I never was very keen on this in the first place.  The idea was to use dcterms for this to support non-SBOL tooling, but that has never really been successfully exploited, so I would suggest that we eliminate the confusing by going to sbol:name.

As for "wasDerivedFroms", this comes from the UML diagrams that label the links to sets of objects.  Are you really suggesting that this variable in the UML diagram for "models" should be changed to "model"?  Or are you suggesting that the UML diagrams should go away?  Note that the specification includes these to assist library developers.  It is not that the specification is written for libSBOLj functions, but rather for SBOL library developers in general.  I would be opposed to eliminating the UML diagrams, and I would also find label edges that represent variables and not RDF tags be changed to names that are not clear.

**Comment by jakebeal** [comment]
Personally, I am generally interacting with SBOL representations either as graphs or as collections of triples. From this perspective, it just makes my life more difficult to have two conflicting sets of names for the same property.  I am thus strongly in favor of having the property names in the spec match the property names as stored in data.

With respect to the particulars:
- I definitely support removing plurals.  In my view, this was never e.g., a "components" set, but was always a set of "component" relations. I will find the diagrams _less_ confusing if they say "component 0..\*" rather than "components 0..\*".  The libraries can rename or not as they like: `doc.getComponents()` and `doc.getComponentSet()` are equally comprehensible to my eye.
- dcterms for title, etc., are useful and well established in our usage. We also may wish to continue expanding usage of dcterms, as we have been doing by starting to use dcterms:alternative (for example, I can see future uses for "dcterms: accessRights" and "dcterms:isReplacedBy").  If there is a strong argument for switching away from DC to another metadata ontology, I'd be fine with that.  I would not, however, wish to start creating our own ontology.

**Comment by cjmyers** [comment]
I think the confusion on this one is due to two questions: 1) Who is the specification written for? 2) Is SBOL a data model or ontology? 

The specification currently is written primarily for library developers to ensure consistency between implementations including API and serializations.  Secondly, it can be used by application developers using these libraries, since they describe a consistent API making it easy to guess the method names to create/fetch content.  It is not as well suited for SPARQL writers, since the tag names are not always consistent with the API names.  Thus, the motivation behind this SEP.  Making this change will reverse these priorities leading to likely more variation in the library APIs and more confusion for library developers.  

If we go this route, then I think it also answers the second question.  Namely, SBOL would simply be an ontology, so the specification should likely be replaced with SBOL-OWL, which presents SBOL as an ontology like Dublin Core or Prov-O.  Maybe this is a good direction, but this is quite a change from the past.  I don't think ontologies are particularly user friendly.  Indeed, I expect application developers will want to hide them, and for example, still use "Name" rather than "Title".  This moves the mapping to more friendly terms to the application and/or library developer rather than the specification.   

I'm okay to bring this to a vote, but if this passes, we should also decide if SBOL is now simply an ontology.

**Comment by jakebeal** [comment]
I think that you're getting a bit ahead of things.  Right now, we're not at the point of deciding between data model and ontology (whatever that means).  With this SEP, I see us trying to step away from the idea that SBOL is merely a _file format_.

In my view, this SEP moves us from file format to a graph-based data model, which can then be represented equivalently in RDF/XML, JSON, various triple formats, etc.  Whether we want to move beyond that to an ontology and automated logical reasoning is an open question. I think there are possibilities worth exploring there, but I don't think we're ready to go there until there's more development and experimentation with SBOL-OWL.

**Comment by cjmyers** [comment]
Here is what I mean, should our specification be UML diagrams like we have now or should it look like this:

https://www.w3.org/TR/prov-o/

I'm ok with either, but I think we need to decide before we start writing the SBOL 3 specification.  I agree that we can approve this SEP and stick with UML diagram based specification, but the reasoning why we are doing this gets weaker.  The fact that the UML diagrams did differ from the tags was one of the reasons that the specification is presented the way it is.  Moving to diagrams like Figure 1 in the Prov-O ontology may make more sense when there are no such differences.

**Comment by udp** [comment]
Jake has pretty much already said everything I could contribute here.

I am happy to extend SEP 032 to include a proposal to replace our UML diagrams with diagrams like those in the PROV spec, which I think are much clearer and more extensible for what is fundamentally a graph-based language.

**Comment by jakebeal** [comment]
I don't have any strong opinion on UML diagrams vs. the sort of graph diagrams in the PROV spec.  I personally find the UML diagrams pretty clear, and we've got a much more complex data model than PROV.  The particular choice of diagram representation, however, does not need to be in the SEP, and I believe should not be there, in order to allow us to experiment with presentation and choose the one that's clearest.

**Comment by cjmyers** [comment]
I agree with Jake that this should not be part of the SEP.  I'm just raising the issue that we seem to be heading towards making SBOL purely an ontology.  If that is true, we need to reconsider how we write a specification for it, but this is a presentation issue.  

I still really don't like "title".  Indeed, the definition of title is: "A name given to the resource.", which makes me wonder why they did not use "name" instead, which I think will be more clear to users.  I agree it is confusing to use dcterms:title and call it "name", so my vote is still to change to "sbol:name".  You can still also have a "dcterms:title", since we allow any annotations outside the SBOL namespace, but I just think name is much cleaner for users of SBOL.  Indeed, it is one of the few parts of SBOL that we have had from the beginning.  I would hate to lose it.  I think it was a mistake to mix dcterms into our Identified class.  We should encourage people to use dcterms, especially for the other things that Jake has mentioned, but I think we should not have ontology terms from other ontologies in our most basic class.  This tight coupling has limited our flexibility and led to this confusion.

**Comment by jakebeal** [comment]
Do you want to change description too?

**Comment by cjmyers** [comment]
For consistency, I think it might be best to change them both to sbol namespace.  This way we would not be dependent on another ontology for the definitions of identified fields.  The other option is to remove these fields and just say use Dublin Core for metadata like this, but I'm not excited about that option, since these are pretty basic fields from the beginning of SBOL.

**Comment by jakebeal** [comment]
I see the converse: every SBOL object currently stored uses Dublin Core for these fields, and changing them to the sbol namespace would entail changing all of those objects.  Thus, leaving them in DC would be the conservative choice from that point of view.  The libraries can keep their accessors with the old names, though (deprecated, of course).

Given our complementary viewpoints, I think it would be useful to hear from a larger number of people at this point.

**Comment by cjmyers** [comment]
Dublin Core will still be allowed, so the way I would implement getName() is return the sbol:name and if not set then return dcterms:title.

**Comment by palchicz** [comment]
Discussion on this item seems to have trailed off. Would the author of the SEP @udp like to jump in?

**Comment by udp** [comment]
I think the consensus is that the issues we were discussing here are separate, so I would be happy for SEP 032 to go to a vote.

**Comment by bbartley** [comment]
I am not opposing a vote, but I'm a little skeptical about this proposal, so my vote is not assured.  As Jake said, this SEP moves us from file format to a graph-based data model.  I'm not sure that's the direction I want to head in.  It's great if you are a developer who is already familiar with RDF.  But if you are not already an expert developer, or if you are a biologist interfacing through tools like Synbiohub, these kind of predicates can look like confusing terminology.  As an example, object oriented Python that uses predicates for attributes is strange and unintuitive from a user perspective:
```
measure.hasUnit = foo
```
vs:
```
measure.unit = foo
```
I think Chris' argument about `name` vs `title` has this same principle at heart.  It is very hard to design good interfaces on top of the SBOL data model, because we tend to think of it only as a data model, without any thought towards how users will eventually interface with it.

**Comment by udp** [comment]
Hi Bryan,

I really don't think the change proposed by SEP 032 is so dramatic.  It's purely just a change in wording to make it more clear how we interoperate with the ontologies that we use. 

> On 9 Jan 2020, at 8:36 pm, bbartley <notifications@github.com> wrote:
> 
> I am not opposing a vote, but I'm a little skeptical about this proposal, so my vote is not assured. As Jake said, this SEP moves us from file format to a graph-based data model. I'm not sure that's the direction I want to head in. It's great if you are a developer who is already familiar with RDF. But if you are not already an expert developer, or if you are a biologist interfacing through tools like Synbiohub, these kind of predicates can look like confusing terminology. As an example, object oriented Python that uses predicates for attributes is strange and unintuitive from a user perspective:
> 
> measure.hasUnit = foo

You would be under absolutely no obligation to call the property "hasUnit" in your Python library.  "unit" is fine.

> I think Chris' argument about name vs title has this same principle at heart. It is very hard to design good interfaces on top of the SBOL data model, because we tend to think of it only as a data model, without any thought towards how users will eventually interface with it.

Thinking about how the users interface with SBOL is the job of the library developers, not the specification.  Consider how much pysbol abstracts over SBOL2 already.  The specification is only a user manual for those working directly with the data model; abstraction is not only permitted but expected.

Since it seems that some discussion is necessary, shall we move this to sbol-dev?

cheers,

James

**Comment by bbartley** [comment]
Hi James,
It's absolutely true that I am using this smaller issue to illustrate a larger point.  More pragmatically, I'd simply like to know if there is a way we can ontologically specify aliases.  Something like:
```
sbol:name sbol:isAlias dcterms:title
```
It's quite likely that an ontological convention for specifying aliases already exists.  I think this might come in handy when we move towards representing SBOL as an ontology.

**Comment by udp** [comment]
Yes, I believe that you would use owl:equivalentProperty for that:

https://www.w3.org/TR/owl-ref/#equivalentProperty-def

Goksel (CC'd because I'm replying by email) would be the better person to check with.

**Comment by cjmyers** [comment]
Given that these mappings are possible.   My vote is even stronger to simply not use dcterms for name/description and to mint SBOL ontology terms for these.  Interesting dcterms:title came up in another meeting this week.  It is good really meant for items like publications.  I think we are abusing it to use it here for parts frankly.   We need to have control over the definition of terms in our Identified class.  As for Prov-O, I'm okay with changing attributes from role to hasRole, if necessary.  I can also get on board with using singular in our diagrams.  I'm just not comfortable using non-intuitive tags in our data model.  Yes, you can make the API different, but then the SBOL specification is no longer useful to people who use our libraries due to the confusion this will cause.

**Comment by jakebeal** [comment]
I can get on board with dropping dcterms:title in favor of sbol:name and dcterms:description in favor of sbol:description.

@udp are you OK with this as well? If so, we can change the SEP to include this and I think we've got consensus to move forward for a vote.

**Comment by udp** [comment]
I am happy with this if it helps to break the deadlock.  Shall I edit it in or does someone want to open a pull request?

**Comment by cjmyers** [comment]
@udp please go ahead and edit as the author.

**Comment by udp** [comment]
Done
