### ISSUE TITLE
SEP 024: SBOL 2.4 measurement related changes

### ISSUE THREAD

**Issue by palchicz** [SynBioDex/SEPs#84]
SEP: https://github.com/SynBioDex/SEPs/blob/master/sep_024.md

**Comment by Fontanapink** [comment]
So in a previously accepted SEP, [SEP 24](https://github.com/SynBioDex/SEPs/blob/master/sep_024.md), there were 2 main propositions:
1) Some _best practices_ propositions
2) Promoting measures to identified

The first point was intended for SBOL 3.2.1 and has been implemented into the specifications, however, we are still missing the second point, which in the original SEP read:

> 2.6 Possible promotion of "measures" to Identified
Given the number of other classes with a potential "measures" property to add in the future, we should also consider changing it to be on Identified rather than on individual classes.

This change was thought for SBOL 2.4.

**Comment by cjmyers** [comment]
Duplicate
