### ISSUE TITLE
SEP 044 -- Unify Structural Information

### ISSUE THREAD

**Issue by jakebeal** [SynBioDex/SEPs#92]
Currently, information about the physical structure of a Component is dispersed across multiple different places: SequenceAnnotations, SubComponents, SequenceConstraints, and Interactions of type Containment. This SEP proposes to unify three of these as subclasses of a single StructuralInformation class, and to generalize containment to a complete set of standard topological constraints.

Full SEP available at: https://github.com/SynBioDex/SEPs/blob/master/sep_044.md

**Comment by cjmyers** [comment]
I'm not excited about this one.  The argument to put SA and SC under one parent seems not particularly compelling.  I think they are separate things.  I also don't think it makes sense to have two classes that are essentially identical (SequenceConstraint and TopologicalConstraint).  My preference would be to just rename SequenceConstraint to Constraint and extend its use to include TopologicalConstraints.  I just feel this is a slippery slope.  We will like need other types of Constraints and I don't like adding a new class for each one.

**Comment by jakebeal** [comment]
I could potentially go with this alternate approach, but would like to hear from others who may have different opinions as well, especially @udp , @graik , and @bbartley

**Comment by graik** [comment]
I have a couple of issues with this one (though it may be cool after a "major revision"):

1. According to SEP 10, SequenceAnnotation shall be renamed to `SequenceFeature`

2.  `SequenceFeature` is **not** to be used for expression of structural information of any kind. This is the job of `SubComponent`. So it seems to me part of this SEP is based on a misunderstanding? SequenceFeature is the same as a genbank sequence feature -- purely for information only. It should therefore **not** be put under an umbrella class together with `SubComponent` that would be, IMO, highly confusing and practically invalidate SEP 10.

3. With `SequenceFeature` (aka SequenceAnnotation) out of the picture, the main point of this proposal would be the introduction of a new "TopologyConstraint" class in order to describe spatial arrangements. I would suggest to rename the SEP accordingly and explicitly state that this SEP *replaces* SEP 30.

I have just browsed over SEP 30 and I must say that I do not like the idea of expressing "contained within" through an interaction either. This indeed looks like a quite awful clutch. So in that sense I would prefer (a modified) SEP 44 over SEP 30. 

Do we really need separate classes for SequenceConstraint and TopologyConstraint? If so, can we ensure that TopologyConstraint is *not* being used as an alternative way of expressing SequenceConstraints? The examples of this SEP seem to suggest that this actually what Bryan and Jake would like to do. But then it would be far better to improve SequenceConstraint rather than creating a duplicate class with overlapping meaning.

**Comment by jakebeal** [comment]
Thank you, @graik:

1. I had forgotten about the name change from SequenceAnnotation to SequenceFeature; I can correct that.

2. I had thought it would be desirable to consolidate such that the `sequenceAnnotation` field didn't appear at all on Components without sequences.  If that's not a worry, then I'm fine dropping SequenceAnnotation from discussion.

3. Given those, I'd be fine just changing `SequenceConstraint` to something like `Constraint` or `DesignConstraint` and expanding the list of constraints.  This would also obviate potential concern about the shared names of constraints, since it's perfectly legitimate to talk about a "contains" relationship for both a 1D structure (sequence) and 3D structure (cell).

Note that SEP 030 talks about a number of things besides containment, so this would only partially replace SEP 030.

**Comment by graik** [comment]
> I had thought it would be desirable to consolidate such that the sequenceAnnotation field didn't appear at all on Components without sequences. If that's not a worry, then I'm fine dropping SequenceAnnotation from discussion.

Well :) I am worried but I would still argue for a "SequenceComponent" aka "Molecule" or "Polymer" subclass of Component to resolve some of the issues discussed in your last SEPs. I think that would be easier and cleaner.

**Comment by jakebeal** [comment]
If we were sticking with BioPAX, I could see doing this, in which one would put `Complex` and `SmallMolecule` in one class, and `Dna*`, `Rna*`, and `Protein` in the other and have done with it.

We have found BioPAX inadequate for the classes that we need to represent, however, which is why SBOL Visual switched to SBO and why SEP 040 is proposed.  Using SBO, there is a much richer class hierarchy, and if we go your route, we will likely need to make a large number of classes that mirror (and inevitably diverge from) SBO. 

This is why my preference is to get our class hierarchy via SBO and to limit the use of properties as needed with restrictions relative to SBO classes, rather than creating new classes in SBOL.

**Comment by cjmyers** [comment]
I like DesignConstraint as a general class for these types of relationships.

**Comment by jakebeal** [comment]
I've updated SEP 037 to just rename SequenceConstraint to DesignConstraint.  If SEP 037 gets adopted, I'll change this to do nothing with classes, but just add values to the table.

**Comment by cjmyers** [comment]
Sounds good to me.

**Comment by jakebeal** [comment]
As SEP 037 is now up for voting and looks good, I have revised SEP 044 to no longer recommend new classes.  Instead, it does only the following:

- Add RECOMMENDED `restriction` values to `Constraint` (and drop the SEP 030 constraint recommendation)
- Rename the `sequenceFeature` property to `feature`, in anticipation of future addition of sibling classes for `SequenceFeature`

**Comment by udp** [comment]
Implemented in SBOL3 draft
